- pipeline.id: logstash_pipeline_partner.conf
  path.config: "/usr/share/logstash/pipeline/logstash_pipeline_partner.conf"

- pipeline.id: logstash_pipeline_users
  path.config: "/usr/share/logstash/pipeline/logstash_pipeline_users.conf"
